In [1]:
print("working")

working

In [3]:
import pandas as pd
print("ready")

ready

In [4]:
import pandas as pd
print("ready")

ready

In [5]:
accounts = pd.read_csv("../data/ravenstack_accounts.csv")
subscriptions = pd.read_csv("../data/ravenstack_subscriptions.csv")
feature_usage = pd.read_csv("../data/ravenstack_feature_usage.csv")
support_tickets = pd.read_csv("../data/ravenstack_support_tickets.csv")
churn_events = pd.read_csv("../data/ravenstack_churn_events.csv")

print("data loaded")

data loaded

In [6]:
accounts.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [7]:
accounts.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [8]:
for name, df in {
    "accounts": accounts,
    "subscriptions": subscriptions,
    "feature_usage": feature_usage,
    "support_tickets": support_tickets,
    "churn_events": churn_events
}.items():
    print("\n", name)
    print(df.isnull().sum())

 accounts
account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

 subscriptions
subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

 feature_usage
usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

 support_tickets
ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

 churn_events
churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

In [9]:
support_tickets['satisfaction_score'] = support_tickets['satisfaction_score'].fillna(0)

In [10]:
accounts['signup_date'] = pd.to_datetime(accounts['signup_date'])

subscriptions['start_date'] = pd.to_datetime(subscriptions['start_date'])
subscriptions['end_date'] = pd.to_datetime(subscriptions['end_date'])

feature_usage['usage_date'] = pd.to_datetime(feature_usage['usage_date'])

support_tickets['submitted_at'] = pd.to_datetime(support_tickets['submitted_at'])
support_tickets['closed_at'] = pd.to_datetime(support_tickets['closed_at'])

churn_events['churn_date'] = pd.to_datetime(churn_events['churn_date'])

print("dates fixed")

dates fixed

In [11]:
for name, df in {
    "accounts": accounts,
    "subscriptions": subscriptions,
    "feature_usage": feature_usage,
    "support_tickets": support_tickets,
    "churn_events": churn_events
}.items():
    print(f"{name}: {df.duplicated().sum()} duplicates")

accounts: 0 duplicates
subscriptions: 0 duplicates
feature_usage: 0 duplicates
support_tickets: 0 duplicates
churn_events: 0 duplicates

In [12]:
df = accounts.merge(subscriptions, on="account_id", how="inner")

df.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier_x,seats_x,is_trial_x,churn_flag_x,...,plan_tier_y,seats_y,mrr_amount,arr_amount,is_trial_y,upgrade_flag,downgrade_flag,churn_flag_y,billing_frequency,auto_renew_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Basic,11,209,2508,False,False,False,False,monthly,True
1,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Pro,20,980,11760,False,False,False,False,monthly,True
2,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Pro,9,441,5292,False,False,False,False,monthly,True
3,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Enterprise,9,1791,21492,False,False,False,False,annual,False
4,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,Basic,102,1938,23256,False,False,False,False,monthly,True

In [13]:
df.shape

(5000, 23)

In [14]:
df = df.merge(churn_events, on="account_id", how="left")

In [15]:
df = df.merge(support_tickets, on="account_id", how="left")

In [16]:
df = df.merge(feature_usage, on="subscription_id", how="left")

In [17]:
df.head()
df.shape

(147896, 46)